pipeline:
  build_image:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-crt-data-recovery
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    dockerfile: Dockerfile
    when:
      event: push

  deploy_to_notprod:
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - kd -f deployment.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
    when:
      event: push

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - kd -f deployment.yml
    secrets:
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER
    when:
      branch: master
      event: push
