---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-crt-data-recovery
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-crt-data-recovery
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jira
        image: quay.io/ukhomeofficedigital/dq-crt-data-recovery
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /mnt/pvc-jira-crt
            name: pvc-jira-crt
          - mountPath: /mnt/dpvc-jira-crt2
            name: pvc-jira-crt2rt
          - mountPath: /mnt/pvc-jira-dc-crtt
            name: pvc-jira-dc-crt
      volumes:
        - name: pvc-jira-crt
          persistentVolumeClaim:
            claimName: pvc-jira-crt
        - name: dpvc-jira-crt2
          persistentVolumeClaim:
            claimName: pvc-jira-crt2
        - name: pvc-jira-dc-crt
          persistentVolumeClaim:
            claimName: pvc-jira-dc-crt
